= Onpier Assignment
:toc: left
:sectnums:

* getActiveUsers
* nonTerminatedUsersWithNoCurrentBorrows
* getUsersWhoBorrowedBooksOnDate
* getBooksBorrowedByUserBetweenDates
* getAvailableBooks

== getActiveUsers

This endpoint retrieves all active users

=== Address

[source,http request,options="nowrap"]
----
GET /api/onpier/assignment/users/actives
----

=== HTTP headers

[cols="1,3"]
|===
|Name |Description

|`+Content-Type+` |  `+application/json+`
|===

=== Response fields

[cols="1,1,3"]
|===
|Name |Type |Description

|`+users+`
|`+List+`
|This field contains information of userId, name, firstName, gender, memberFrom, memberTill
|===

=== HTTP request example

[source,http request,options="nowrap"]
----
curl --location --request GET /api/onpier/assignment/users/actives'
--header 'Content-Type: application/json

----

=== HTTP response example

[source,http response,options="nowrap"]
----
HTTP/1.1 200 OK
Content-Type: application/json
{
 [
    {
        "userId": "c2cc48f8-3883-450b-badb-2d25a9aa05fa",
        "name": "Chish",
        "firstName": "Elijah",
        "gender": "MALE",
        "memberFrom": "01/14/1970",
        "memberTill": "N/A"
    },
    {
        "userId": "156c9b8f-9971-441f-8e24-b2d801c2251d",
        "name": "Zhungwang",
        "firstName": "Ava",
        "gender": "FEMALE",
        "memberFrom": "01/19/1970",
        "memberTill": "N/A"
    }
 ]
}
----

== nonTerminatedUsersWithNoCurrentBorrows

Get non-terminated users who have no current borrows

=== Address

[source,http request,options="nowrap"]
----
GET /api/onpier/assignment/users/nonTerminate/withoutBorrows
----

=== HTTP headers

[cols="1,3"]
|===
|Name |Description

|`+Content-Type+` |  `+application/json+`
|===

=== Response fields

[cols="1,1,3"]
|===
|Name |Type |Description

|`+users+`
|`+List+`
|This field contains information of userId, name, firstName, gender, memberFrom, memberTill
|===

=== HTTP request example

[source,http request,options="nowrap"]
----
curl --location --request GET /api/onpier/assignment/users/nonTerminate/withoutBorrows'
--header 'Content-Type: application/json

----

=== HTTP response example

[source,http response,options="nowrap"]
----
HTTP/1.1 200 OK
Content-Type: application/json
{
 [
    {
        "userId": "c2cc48f8-3883-450b-badb-2d25a9aa05fa",
        "name": "Chish",
        "firstName": "Elijah",
        "gender": "MALE",
        "memberFrom": "01/14/1970",
        "memberTill": "N/A"
    },
    {
        "userId": "156c9b8f-9971-441f-8e24-b2d801c2251d",
        "name": "Zhungwang",
        "firstName": "Ava",
        "gender": "FEMALE",
        "memberFrom": "01/19/1970",
        "memberTill": "N/A"
    }
 ]
}
----


== getUsersWhoBorrowedBooksOnDate

Retrieves users who borrowed books on the specified date

=== Address

[source,http request,options="nowrap"]
----
GET /api/onpier/assignment/users/borrowed
----

=== HTTP headers

[cols="1,3"]
|===
|Name |Description

|`+Content-Type+` |  `+application/json+`
|===

=== Response fields

[cols="1,1,3"]
|===
|Name |Type |Description

|`+users+`
|`+List+`
|This field contains information of userId, name, firstName, gender, memberFrom, memberTill
|===

=== HTTP request example

[source,http request,options="nowrap"]
----
curl --location '/api/onpier/assignment/users/borrowed?date=05%2F14%2F2008'
----

=== HTTP response example

[source,http response,options="nowrap"]
----
HTTP/1.1 200 OK
Content-Type: application/json
{
 [
    {
        "userId": "c2cc48f8-3883-450b-badb-2d25a9aa05fa",
        "name": "Chish",
        "firstName": "Elijah",
        "gender": "MALE",
        "memberFrom": "01/14/1970",
        "memberTill": "N/A"
    },
    {
        "userId": "156c9b8f-9971-441f-8e24-b2d801c2251d",
        "name": "Zhungwang",
        "firstName": "Ava",
        "gender": "FEMALE",
        "memberFrom": "01/19/1970",
        "memberTill": "N/A"
    }
 ]
}
----

== getBooksBorrowedByUserBetweenDates

Returns a list of books that a user has borrowed within a specified date range

=== Address

[source,http request,options="nowrap"]
----
GET /api/onpier/assignment/books/borrowed/by-user
----

=== HTTP headers

[cols="1,3"]
|===
|Name |Description

|`+Content-Type+` |  `+application/json+`
|===

=== Response fields

[cols="1,1,3"]
|===
|Name |Type |Description

|`+books+`
|`+List+`
|This field contains information of title, publisher, genre, author
|===

=== HTTP request example

[source,http request,options="nowrap"]
----
curl --location '/api/onpier/assignment/books/borrowed/by-user?endDate=07%2F16%2F2007&userId=7f731abd-589c-418d-bb79-fb5ec27d3e16&startDate=06%2F15%2F2007'
----

=== HTTP response example

[source,http response,options="nowrap"]
----
HTTP/1.1 200 OK
[
    {
        "title": "New Markets & Other Essays",
        "author": "Drucker, Peter",
        "publisher": "Penguin",
        "genre": "ECONOMICS"
    }
]
----


== getAvailableBooks

Returns a list of all books that are currently available for borrowing

=== Address

[source,http request,options="nowrap"]
----
GET /api/onpier/assignment/books/available
----

=== HTTP headers

[cols="1,3"]
|===
|Name |Description

|`+Content-Type+` |  `+application/json+`
|===

=== Response fields

[cols="1,1,3"]
|===
|Name |Type |Description

|`+books+`
|`+List+`
|This field contains information of title, publisher, genre, author
|===

=== HTTP request example

[source,http request,options="nowrap"]
----
curl --location '/api/onpier/assignment/books/available'
----

=== HTTP response example

[source,http response,options="nowrap"]
----
HTTP/1.1 200 OK
[
    {
        "title": "Age of Discontuinity, The",
        "author": "Drucker, Peter",
        "publisher": "Random House",
        "genre": "ECONOMICS"
    },
    {
        "title": "Age of Wrath, The",
        "author": "Eraly, Abraham",
        "publisher": "Penguin",
        "genre": "HISTORY"
    },
    {
        "title": "Aghal Paghal",
        "author": "Deshpande, P L",
        "publisher": "Mauj",
        "genre": "NONFICTION"
    }
]
----

== HTTP response codes

NOTE: We use conventional HTTP response codes to indicate the success or failure of an API request.

* HTTP code 200 indicates success.
* HTTP code 400 indicates invalid params.
* HTTP code 500 indicates internal errors.


== Version history

[cols="1,2,3"]
|===
|Version |Author| Description

|1.0  |Mehdi Qanbarzade |First Version
|===
